- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker
    redmine_port: 80

  pre_tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Copy environment file
      ansible.builtin.template:
        src: .env.j2
        dest: .env
        mode: "0644"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      tags: deploy

    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine
        image: "redmine:6.0.7-alpine3.23"
        restart_policy: always
        state: started
        env_file: .env
        ports: "{{ redmine_port }}:3000"
      tags: deploy

- hosts: webservers
  become: true

  vars:
    datadog_api_key: "{{ vault_datadog_api_key }}"
    datadog_site: "datadoghq.eu"

  tasks:
    - name: Import the Datadog Agent
      import_role:
        name: datadog.dd.agent
      tags: monitoring
