$ANSIBLE_VAULT;1.1;AES256
39613161313362613161613139383730656236656638653630633233656238646434656164333364
6535313561623861306430393966626631323833333363620a333632643734393636353162646135
37636463316438373132393735336661626439623363366231353261353939393938333063653631
6436303535336266610a626239633661663865306333376333326239303662653536373465396161
39623538653761333435316662343330393335653966383235613964333836353436623937303763
37613664663763343639646566623336363263363333393963646437373465303161646439303464
34386364326430613564626530313764623465363461326664363131613435666566666662383731
35623239323936326439373635333138326565333130383533613633323065363466656262303661
61373361323830393930613632393035323132666335363732376262373631373230643938323736
6364353064666639363437343163656139376666306465636364
